# Generated by Django 4.0 on 2021-12-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_beat_mp3_beat_wave_beat_wrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='artist',
        ),
        migrations.AddField(
            model_name='beat',
            name='artist',
            field=models.ManyToManyField(to='beats.Artist'),
        ),
    ]
