# Generated by Django 4.0 on 2021-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_remove_beat_artist_beat_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='artist',
            field=models.ManyToManyField(help_text='Select Artists for the beat', to='beats.Artist'),
        ),
    ]
