# Generated by Django 4.0.1 on 2022-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_alter_beat_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='wrap',
            field=models.ImageField(default='images/wraps/S.png', upload_to='images/wraps/'),
        ),
    ]
