# Generated by Django 4.0.1 on 2022-01-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_alter_beat_wrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='wrap',
            field=models.ImageField(default='images/wraps/S.svg', upload_to='images/wraps/'),
        ),
    ]
